### ISSUE TITLE
Compose does not work as expected (caching)

### ISSUE THREAD

**Issue by BerkeleyTrue** [stampit-org/react-stampit#24]
Adding react-routers navigation mixin to a component. The component has displayName 'lecture'. The mixin has no displayName, as it is a mixin. As per examples in README, I expected this to work fine. See: https://github.com/stampit-org/react-stampit#what-is-this

At first I was annoyed that my mixins had to have displayNames in order to actually get mixed in. I see now that the API does state it expects stamps, not just mixins. This just means that the README examples need to be updated to actually create stamps with displayNames not just throw in plain mixins (mixins as created for the react community).

But then I noticed something odd. The displayName used to get from cache is the displayName of the last stamp in the `stamps` array in the compose method. The last stamp is the context of the compose function. This means if I use the compose method with a stamp created with a property 'displayName', the stamp I am calling compose from will be used to check and get from cache. If I'm looking at this right, the compose method will never work as expected when the context has a 'displayName' property.

Looking through `tests/compose` I see `displayName` is never used in test. I also see that you do test using POJO and that was intended to be used with plain react mixins.
## A Proposal: Remove Stamp Caching

Caching of stamps is something that should be done in user land, and right before handing of to React. I think this issue is a good example of why not to cache internally. If I hadn't dived into the source I wouldn't have known that stamps where being cached. In fact the word `cache` is not used anywhere in the README. And only comes up in one PR.

**Comment by troutowicz** [comment]
I'm going to be quite busy this week, I may not get a chance to take a look at this until the weekend. Thanks for filing the issue and proposal.

**Comment by troutowicz** [comment]
> At first I was annoyed that my mixins had to have displayNames

This is not true.

In react-stampit, mixins are stamps. They can be represented in two ways.

As a stamp:

``` js
const mixin = stampit(null, {
  // description object props
});
```

Or as a POJO:

``` js
const mixin = {
  // description object props
};
```

The latter is just shorthand for the former. Neither require the `displayName` prop. When the `displayName` prop is not used, react-stampit adds a default `displayName`, 'ReactStamp'.(React.createClass will do similar but names it 'ReactClass').

It should also be mentioned here that components without a declared `displayName` will not get cached. 

>  The displayName used to get from cache is the displayName of the last stamp in the stamps array in the compose method.

Correct.

> The last stamp is the context of the compose function.

This is true and I can definitely see the documentation has some holes. The caching system was implemented recently and has not had a lot of exposure.

Let me bring up the reason the caching system was implemented.

React has some [issues](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375). The big one deals with a project unexpectedly running two instances of React. This can happen in a number of ways as the article mentions, and the way react-stampit attempts to tackle the problem is by recommending dependency injection.

Creating a component the usual way:

``` js
import React from 'react';

export default stampit(React, {
  // description object props
});

```

Recommended way with DI:

``` js
export default React => stampit(React, {
  // description object props
});
```

You will notice the component does not import the React library. This is the purpose of DI. With DI, a component factory is returned instead of the component.

``` js
import React from 'react';

import componentFactory from './component';

const component = componentFactory(React);
```

The caching exists to handle what Node's module caching cannot. When exporting a DI based React component, Node will cache the exported value. (just like it does with any module) But what is being cached is the component factory, not the actual component (aka stamp, aka factory). This means every component returned from the component factory will be unique. This will not affect the usability of DI based React components, but it does affect things like testing (utilities like `TestUtils.findRenderedComponentWithType` that compare component constructors) and possibly performance when a component is created multiple times.

The new structure of React 0.14 may have fixed this multiple instance problem, I have not had time to look into it.

Now, regarding the problem with `displayName` and `.compose`, this is a possible solution:

``` js
import React from 'react';

import mixin from './mixin';
import componentFactory from './component';

let component = componentFactory(React);
component.displayName = 'newCacheableComponent';

export default component.compose(mixin);
```

I'd love to hear your thoughts on other possible solutions.

**Comment by BerkeleyTrue** [comment]
> The big one deals with a project unexpectedly running two instances of React. 

This is due to importing 'react' and 'react/addons' in the same project and the fact that React keeps track of context in a module. This is indeed fixed in 0.14 by the removal of ReactContext. Also, this is not something this module should try to tackle. This module should only be concerned with creating stamps for react components in a stampit way that is friendly towards the user.

I don't think DI solves this issue in 0.13 as the issue lies in how modules are imported(or required) and how the system is deduped (the main culprit being browserify as webpack automatically dedupes), at least from the point of view of a complete app. All it takes if for a user to use 'react/addons' in one module and things will break. And again not really the concern of this module.

Plus this then feels like you are forcing the user to use it with DI instead of how they like it. I personally do not like:

``` js
import React from 'react';

import mixin from './mixin';
import componentFactory from './component';

export default component.compose(mixin);
```

I like my components to be self contained and complete before being exported and making the caching internal and automatic forces the user into a what is supposed to be an optional way of doing things. It's easier for others to reason what the component does when they can see the factory and it's mixins in one file. Not saying the above is wrong, just not to my taste and doesn't jive with the way I structure my file directories.

> The caching exists to handle what Node's module caching cannot

I understands is use, but it should not be internal. What if someone has a favorite caching library they want to use and then end up double caching? At the most this library should expose the caching module and disable it's automatic behavior allowing the user to use it or not. But I am of the opinion that it should not have caching at all. This libraries concern should only be creating react stamps. 

>  Now, regarding the problem with displayName and .compose, this is a possible solution:

What if I want to do this?

``` js
import React from 'react';

import mixin from './mixin';
import mixin1 from './mixin1';
import mixin2 from './mixin2';
import mixin3 from './mixin3';

import componentFactory from './component';

export default component.compose(mixin).compose(mixin1).compose(mixin2).compose(mixin3);
```

Now I have to to come up with a name for each one of these and a temp file in-between, even though I just want it to have the name that component has. Just because I am adding mixins doesn't mean I am changing the intent, and the name of a component should describe its intent. This is more of a hack then a solution.

My PR for this issue is a solution which just removes caching.

**Comment by troutowicz** [comment]
> This is due to importing 'react' and 'react/addons'

This in itself is not a cause of multiple instances afaik. You can require both in a project while never creating multiple instances. See this React [issue](https://github.com/facebook/react/issues/2456) for more info and a scenario where this does hold true. The other article I linked earlier describes other scenarios.

> I don't think DI solves this issue in 0.13

Using dependency injection guarantees the version and instance of React that the component will use. What if the project is depending on React via CDN? We can't have components importing a different version of React. I'd love to hear @ericelliott's thoughts here as he was the one who pointed this out to begin with.

``` js
import React from 'react';

import mixin from './mixin';
import componentFactory from './component';

let component = componentFactory(React);
component.displayName = 'newCacheableComponent';

export default component.compose(mixin);
```

I didn’t expect the above design to actually be used in projects, it was just an example. In an actual project, I would say any needed composition would happen in the apps top level component or in the child component itself.

> Just because I am adding mixins doesn't mean I am changing the intent, and the name of a component should describe its intent.

In my opinion, adding mixins to a component changes the intent. You are composing a new component.

I do now realize that this caching idea may have been rushed. At the time it looked like a good solution, but I obviously did not consider all use cases. I agree that this module's only concern should be creating components. The caching was meant to fix what DI broke, while being optional and for the most part invisible to the user.... but it looks like caching is breaking more than it fixes.

If we can guarantee that going forward with React 0.14 there will be no more multiple instance / different version problems, then I am all for removing the cache functionality. But if not, we should consider ways to make caching work in order to have fully functional DI support.

**Comment by BerkeleyTrue** [comment]
> In my opinion, adding mixins to a component changes the intent. You are composing a new component.

Yes, we are two different people with two different opinions. Now where should this library, which is intended to be used by many different people, lay?

Where I'm coming from: If I create a component, named `Question`, and that component needs a mixin to navigate (`Navigation` mixin), and my intent is for this component is to navigate (among other things), the the first component created is not a full component and is incomplete and dysfunctional without that mixin.

In reality, it is an intermediate component. Once the mixin is added, now it is a fully functional component, my `Question` component. I'm adding abilities indented to be used internally in the intermediate component. The `Navigation` mixin cannot be considered a component, neither can the unmixed `Question` component, as it won't work on its own.

**Comment by BerkeleyTrue** [comment]
> The caching was meant to fix what DI broke

Why not do the caching externally and give the user choice? Instead, why not explain to them why caching is necessary when doing DI and do not force those not using DI to use caching?

**Comment by troutowicz** [comment]
> Yes, we are two different people with two different opinions.

I walked right into that one...

Your intermediate component design makes sense and I see why the current state of this lib would cause you issues.

> Why not do the caching externally and give the user choice?

Yep, this is looking like the only good way to handle this.

``` js
import stampit from 'react-stampit';
import { cache } from 'react-stampit/utils';

export default React => cache(
  stampit(React, {
    displayName: 'Component',

    // description object props
  })
);
```

Line [133](https://github.com/stampit-org/react-stampit/blob/master/src/index.js#L133) and lines [177](https://github.com/stampit-org/react-stampit/blob/master/src/index.js#L177) through 179 would still be used. (I think, have not tested)

Another option, while still being internal, would be to stop using `displayName` as a toggle and be more explicit with a `_cache` property toggle.

``` js
import stampit from 'react-stampit';

export default React => stampit(React, {
  _cache: true,
  displayName: 'Component',

  // description object props
});
```

This would be documented, and it would optional.

**Comment by BerkeleyTrue** [comment]
> Line 133 and lines 177 through 179 would still be used. (I think, have not tested)

If the caching is external then I think that is fine. The caching would happen after a user composes a component but before exporting as apposed to caching before composition which is where the problem is. 

I'm not sure if using the displayName is a good idea. Most caching schemes generate a unique identifier each item its caching, right?

**Comment by troutowicz** [comment]
I'm open to using a different unique identifier. I need to think about this some more.

**Comment by BerkeleyTrue** [comment]
:+1:
