### ISSUE TITLE
Strip state prop in favor of init?

### ISSUE THREAD

**Issue by troutowicz** [stampit-org/react-stampit#31]
It has been mentioned a few times now how an `init` method prop in the description object would be useful. See issues #21, #29. What if the API was changed, removing the `state` prop of the description object and in it's place have more flexible `init` method prop?

`init` would behave just as `init` behaves in the core stampit library, so component state would be set like:

``` js
stampit(React, {
  init() {
    this.state = { ... }
  }
});
```

instead of

``` js
stampit(React, {
  state: { ... }
});
```

This is more typing for declaring component state, but the `init` method would allow a wide range of use cases currently not possible. It also makes sense to have a constructor like method at the stamp level (`init`) as well as the React level (`componentWillMount`).

**Comment by BerkeleyTrue** [comment]
Why not both? That way it's just a minor version bump instead of a breaking change.

**Comment by troutowicz** [comment]
Yeah that's a better idea. :)

**Comment by BerkeleyTrue** [comment]
:+1: for that!

**Comment by ericelliott** [comment]
Why not add `.compose()` and `initializers` seeing as how we need to get moving toward the open [Stamp specification](https://github.com/stampit-org/stamp-specification) anyway?

IMO, the best thing about the stamp specification is that all the stampit idioms will still work, _and_ we get full control of the stamp API so that it's a breeze to offer the React-specific stuff.

**Comment by ericelliott** [comment]
Also, :+1: for doing both, not stripping `state`.
