### ISSUE TITLE
Converting existing ES6 React Components to stamps

### ISSUE THREAD

**Issue by josephfinlayson** [stampit-org/react-stampit#34]
```
import stamp from 'react-stampit/lib/utils/decorator';

class Component extends React.Component {

    render(){
        return (<div />)
    }
}

export default stamp(Component)
```

Is something like this possible? I'd like to convert my classes to stamps centrally without using decorators.

**Comment by BerkeleyTrue** [comment]
There is an undocumented feature to do this [here](https://github.com/stampit-org/react-stampit/blob/master/src/utils/decorator.js#L43)

**Comment by troutowicz** [comment]
Well, it is documented... that function is the decorator function. It just so happens that it can also work as a regular function. So I guess in that sense it is undocumented. :)

**Comment by BerkeleyTrue** [comment]
Sorry about that, didn't see it. Yeah class decorators are just functions and can be used as such.

**Comment by joshdmiller** [comment]
I don't consider it undocumented either, but it's buried under [advanced use cases](https://github.com/stampit-org/react-stampit/blob/e74fe0739597b4683c50d6e8dff8224e1b7ab06a/docs/advanced.md#class-decorator). While I think it is better for new react-stampit people to think in the paradigm covered in the main readme, perhaps the "shortcut" decorator option should be at least mentioned there as well.

It might also be beneficial to document in the advanced use cases the plain function usage since decorators are not in wide use yet (babel still has them at [stage 1](http://babeljs.io/docs/usage/experimental/)).

**Comment by troutowicz** [comment]
I'd gladly accept a PR with those changes!

**Comment by troutowicz** [comment]
Closing, @josephfinlayson reopen if you still have questions.
